### ISSUE TITLE
[FEATURE] Step of email / phone number validation code

### ISSUE THREAD

**Issue by SergeiLabutin** [NearHuscarl/flutter_login#139]
**Is your feature request related to a problem? Please describe.**
Sign up and sometimes sign in can require enter code (3-6 digits) with user received via email or sms. I can make it with additional controller and page, but I believe, in this plugin it will be better.

**Describe the solution you'd like**
Add params for activation validation code step. You can use [this plugin](https://pub.dev/packages/pin_code_fields) as input field

**Additional context**
In [this video](https://youtu.be/x8xEkNCd3Vg?t=873) created verification step with flutter_login plugin

**Comment by juliansteenbakker** [comment]
I believe this functionality will be implemented with changes currently in the confirmation-card branch together with #15.

**Comment by Huzhengtao** [comment]
Confirmation verification code is indispensable for registering email / mobile account. The priority of this function should be very high. I really need this

**Comment by BatanGaming** [comment]
Will it handle this case:

- User signs-up
- New user created in database
- User closes app without successful confirmation
- User tries to log-in but he can't because he didn't confirm his email
- User tries to sign-up again but he can't too because user with this email already exists

I guess it can be done with redirect to confirm screen after success login if email isn't confirmed.

**Comment by rajd90** [comment]
is there an ETA on this feature?
for the moment i've built my confirmation flow by showing an ugly dialog over the main login screen.

**Comment by xdkaka** [comment]
+1
