### ISSUE TITLE
ButtonProvider title causes padding to side of authCard

### ISSUE THREAD

**Issue by juliansteenbakker** [NearHuscarl/flutter_login#184]
**Describe the bug**
ButtonProvider title causes some kind of padding to the right of the authcard.
The text also keeps being visible while animation is done.

**Screenshots**
![Screenshot_20210607-145653](https://user-images.githubusercontent.com/20091319/121020507-b62c8d80-c7a0-11eb-8f62-80c99dbc6a78.png)

**Comment by malta895** [comment]
I managed to fix the issue of the text still being visible, in 9eb32d6fd7ee132aeddd6e0e4dd4bc5f60716d9b; I put the same animation as the buttons, making it consistent with the rest of the card. 

I can't figure out how to get rid of the padding though, I think it is due to the fact that the card becomes too high with  the providers title, and after the rotation it causes this glitch.

**Comment by surister** [comment]
It happens even if you don't use providers at all.
