### ISSUE TITLE
How to remove sign up button 

### ISSUE THREAD

**Issue by harrypatel07** [NearHuscarl/flutter_login#36]
Hello,

Super awesome login screen.

As on my application, there is no signup only login and forgot password things are there, so I want to remove the signup button, how can I hide or remove signup button.

Thanks

**Comment by vincperrone** [comment]
I have the same question.

Great login screen by the way!

Thanks!

**Comment by savasadar** [comment]
I need same feature but There is not.

**Comment by nekoto-kun** [comment]
I think it could be done with a little hack. There is a private widget that builds the switch button (login to signup) named ```_buildSwitchAuthButton``` in ```auth_card.dart``` file and the widget appearances can be commented out to make the button to not showing up.

However, I have no idea to put that trick in projects that depend on this package, since it's still labeled as required.

**Comment by achamene** [comment]
Same issue here.
I want to remove the signup button.
Who knows how to do it?

**Comment by von-maurus** [comment]
Same here!! plz add this feature

**Comment by smobx1** [comment]
same..

**Comment by juliansteenbakker** [comment]
Duplicate of #19
