### ISSUE TITLE
onSubmitAnimationCompleted() always get called......what if the password is incorrect and you wanti remain on the same screen.

### ISSUE THREAD

**Issue by debugger13524** [NearHuscarl/flutter_login#92]

**Comment by TafadzwaD** [comment]
From my understanding , return null signifies a success message, i.e a successful login. This will trigger the onSubmitAnimationCompleted() animation.. In the event that you want to remain on the same screen due to an incorrect password do like so.. If password is incorrect then `return 'Message of your choice'`. The Message of your choice will be displayed as an error flush bar and the onSubmitAnimationCompleted() will not get called

**Comment by TafadzwaD** [comment]
So this is not a bug per se
